### ISSUE TITLE
YouTube Videos Error

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#10]
**[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** reported:

Attempting to play an embedded video anywhere on the site besides the front page results in the video seeming to prepare to load but suddenly turn into 
'Team9000 - Error
The requested page could not be found.'

Mantis severity: **major**
Mantis priority: **high**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000010](https://bugs.team9000.net/view.php?id=10)** by **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** at Fri Feb 10 05:50:20 2012.

**Comment by pon4importer** [comment]
At Fri Feb 10 05:50:20 2012 **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** attached **[Screen Shot 2012-02-10 at 1.49.30 PM.png](https://bugs.team9000.net/file_download.php?file_id=2&type=bug)**, 92317 bytes, *image/png*.

**Comment by sonicsnes** [comment]
At Fri Feb 10 06:10:09 2012:

What browser is this?

**Comment by pon4importer** [comment]
At Fri Feb 10 08:49:18 2012 **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** commented:

Google Chrome 16.0.912.77
Mac OSX 10.7.2
All software updates installed

The embedded videos will still play in Safari.
Also note specifically the fact that rsmv's video on the homepage still plays properly on Chrome.

**Comment by sonicsnes** [comment]
At Fri Feb 10 08:57:59 2012:

link to an example video please

**Comment by pon4importer** [comment]
At Fri Feb 10 09:11:14 2012 **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** commented:

Example video?
(All embedded videos besides the homepage rsmv video won't play, I went through playing a lot of videos in the The place where the poop I find on YouTube goes thread as well just to check. The random video of the moment on the homepage will not play.)

**Comment by pon4importer** [comment]
At Fri Feb 10 13:36:19 2012 **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** attached **[Main Page Video Playing Fine While Random Video Of The Moment Gives The Error.png](https://bugs.team9000.net/file_download.php?file_id=3&type=bug)**, 408921 bytes, *image/png*.

**Comment by sonicsnes** [comment]
At Wed Feb 15 18:40:13 2012:

I still can't seem to reproduce this. Can you make the glitch happen, then do the following:

ctrl+shift+I
right click on the top html element
click "Copy as HTML"
Paste the html into a file, then attach it.

**Comment by pon4importer** [comment]
At Thu Feb 16 00:21:53 2012 **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** commented:

Ctrl+Shift+I? I tried the Mac equivalent of that, Cmd+Shift+I, didn't do anything, so I opened up the page source and copied the html.

**Comment by pon4importer** [comment]
At Thu Feb 16 12:12:07 2012 **[cacher](https://bugs.team9000.net/view_user_page.php?id=42)** commented:

Go into developer tools

click the wrench

Then click  "Tools"

Then Click "Developer Tools"

**Comment by pon4importer** [comment]
At Thu Feb 16 14:22:12 2012 **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** commented:

Cacher, I did that, but I don't get an option to copy it as HTML anywhere...

**Comment by pon4importer** [comment]
At Tue Apr  3 03:15:43 2012 **[mcfar45](https://bugs.team9000.net/view_user_page.php?id=8)** commented:

I get the same issue on Chrome 18.0.1025.142 on Windows 7.I will attach an HTML log in a moment.

**Comment by pon4importer** [comment]
At Tue Apr  3 03:27:53 2012 **[mcfar45](https://bugs.team9000.net/view_user_page.php?id=8)** attached **[mcfar45Chrome18.txt](https://bugs.team9000.net/file_download.php?file_id=12&type=bug)**, 73104 bytes, *text/plain*.

**Comment by pon4importer** [comment]
At Tue Apr  3 03:49:50 2012 **[mcfar45](https://bugs.team9000.net/view_user_page.php?id=8)** commented:

I have now attached the HTML of the page.

**Comment by pon4importer** [comment]
At Thu Apr  5 04:04:36 2012 **[mcfar45](https://bugs.team9000.net/view_user_page.php?id=8)** commented:

I just tested this with Firefox 11 on Windows 7 and the same issue is occurring.

**Comment by pon4importer** [comment]
At Mon Apr  9 06:30:27 2012 **[mcfar45](https://bugs.team9000.net/view_user_page.php?id=8)** commented:

I have worked out the cause of this issue. It only happens if you have FastestChrome or FastestFox installed as an addon. By removing the offending extension the problem should be solved.

**Comment by pon4importer** [comment]
At Tue Apr 10 09:59:02 2012 **[vincent2128](https://bugs.team9000.net/view_user_page.php?id=35)** commented:

Ehh.
Temporarily disabling FastestChrome through the Extensions menu gets the YouTube videos to work as well, if you don't want to outright uninstall FastestChrome.

**Comment by sonicsnes** [comment]
At Thu May 24 21:51:27 2012:

Enjoy your youtube videos again.

**Comment by pon4importer** [comment]
At Mon Aug 13 22:23:27 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:06:53 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
