### ISSUE TITLE
Promotion Warp should run automatically

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#13]
-

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **game.mcclassic**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000013](https://bugs.team9000.net/view.php?id=13)** at Fri Feb 10 07:13:54 2012.

**Comment by sonicsnes** [comment]
At Mon Aug 13 22:22:08 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:07:16 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
