### ISSUE TITLE
Steam group event import

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#15]
Team9000 Website should import events from the Steam Group

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000016](https://bugs.team9000.net/view.php?id=16)** at Sat Feb 11 02:34:42 2012.

**Comment by sonicsnes** [comment]
At Tue Apr  9 13:22:41 2013:

no longer valid with new event system

**Comment by sonicsnes** [comment]
At Tue Apr  9 13:22:41 2013 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:11:23 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
