### ISSUE TITLE
SSO system should operate out of a single JS file

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#16]
-

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web.sso**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000017](https://bugs.team9000.net/view.php?id=17)** at Sat Feb 11 12:52:10 2012.

**Comment by sonicsnes** [comment]
At Wed Aug 15 04:07:56 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:11:30 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
