### ISSUE TITLE
SSO bar should have dropdown for "More"

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#17]
-

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web.sso**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000018](https://bugs.team9000.net/view.php?id=18)** at Sat Feb 11 12:52:56 2012.

**Comment by sonicsnes** [comment]
At Mon Aug 13 22:25:55 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:11:37 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
