### ISSUE TITLE
SSO should utilize CORS on browsers that support it

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#19]
New browsers (chrome) is starting to drop cookies from XDRs using JSONP as the carrier. This breaks NKSSO on any domains that aren't on the .team9000.net namespace. As all the affected (and future affected) browsers support CORS, the system should use these requests instead.

Mantis severity: **major**
Mantis priority: **normal**
Mantis project: **web.sso**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000030](https://bugs.team9000.net/view.php?id=30)** at Sat Feb 11 19:16:57 2012.

**Comment by sonicsnes** [comment]
At Sun Feb 12 10:36:16 2012:

CORS implemented. System now requires an exception if third party cookies are disabled.

**Comment by sonicsnes** [comment]
At Mon Aug 13 22:25:55 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:58:29 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
