### ISSUE TITLE
Add SSL to map.team9000.net

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#20]
**[cacher](https://bugs.team9000.net/view_user_page.php?id=42)** reported:

turn http://map.team9000.net into https://map.team9000.net

Mantis severity: **feature**
Mantis priority: **low**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000031](https://bugs.team9000.net/view.php?id=31)** by **[cacher](https://bugs.team9000.net/view_user_page.php?id=42)** at Sun Feb 12 10:42:14 2012.

**Comment by sonicsnes** [comment]
At Thu Dec 13 02:21:51 2012:

decided against this one

**Comment by pon4importer** [comment]
At Thu Dec 13 02:21:51 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:58:33 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
