### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#24]
**[david](https://bugs.team9000.net/view_user_page.php?id=64)** reported:

Hello there. I would appreciate if you can change my name, TheNinjaDavid, to David. Thanks for your help! Hoped this wasn't too much trouble.

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web.namechange**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000035](https://bugs.team9000.net/view.php?id=35)** by **[david](https://bugs.team9000.net/view_user_page.php?id=64)** at Sun Feb 12 20:12:55 2012.

**Comment by sonicsnes** [comment]
At Sun Feb 12 20:19:48 2012:

Older accounts are more difficult to transfer. I will need to check your name on all services in the network (wiki, t9k.me, gallery, launch, ... bugs).

**Comment by pon4importer** [comment]
At Thu Dec 13 02:03:32 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:58:47 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
