### ISSUE TITLE
Number of new posts in a watched/visited thread

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#25]
**[hawke](https://bugs.team9000.net/view_user_page.php?id=59)** reported:

I suggest every thread in a forum list gets a clickable link that displays the number of new posts in a thread since last visit. Example: 
-*Thread Name*_____________*x new posts!*
-*username*,*date* 
Clicking on this *x new posts!* link will lead to the new posts mentioned.
Can also replace the blue dot currently used to go to the first unread post.

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000026](https://bugs.team9000.net/view.php?id=26)** by **[hawke](https://bugs.team9000.net/view_user_page.php?id=59)** at Sat Feb 11 15:02:03 2012.

**Comment by sonicsnes** [comment]
At Thu May 24 22:24:11 2012:

Don't want to clutter the interface. The blue dot is the indicator for this, and if you wish to see how MANY new posts, you can check them.

**Comment by pon4importer** [comment]
At Wed Aug 15 04:07:56 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:12:31 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
