### ISSUE TITLE
Double Commenting Issue

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#26]
**[cacher](https://bugs.team9000.net/view_user_page.php?id=42)** reported:

Comment is posted multiple times.

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000037](https://bugs.team9000.net/view.php?id=37)** by **[cacher](https://bugs.team9000.net/view_user_page.php?id=42)** at Tue Feb 14 04:59:29 2012.

**Comment by pon4importer** [comment]
At Tue Feb 14 04:59:29 2012 **[cacher](https://bugs.team9000.net/view_user_page.php?id=42)** attached **[Capture4.PNG](https://bugs.team9000.net/file_download.php?file_id=5&type=bug)**, 128345 bytes, *image/png*.

**Comment by sonicsnes** [comment]
At Tue Feb 14 05:20:28 2012:

I don't see any of the additional posts (it seems to be local), and I have no intentions of supporting LNBlog more than I need to. Eventually, the entire system will be re-written from scratch by me (part of project web.rebuild).

**Comment by pon4importer** [comment]
At Wed Aug 15 04:07:56 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:58:56 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
