### ISSUE TITLE
Watched threads list/page

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#26]
**[hawke](https://bugs.team9000.net/view_user_page.php?id=59)** reported:

A page containing all of the threads that you watch/posted in(unless unwatched).
Could replace "Latest alerts" as the main method of returning to watched threads.
Works best with Issue [mantis:0000026](https://bugs.team9000.net/view.php?id=26).

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000027](https://bugs.team9000.net/view.php?id=27)** by **[hawke](https://bugs.team9000.net/view_user_page.php?id=59)** at Sat Feb 11 15:03:06 2012.

**Comment by sonicsnes** [comment]
At Thu May 24 22:25:43 2012:

This already exists:
https://www.team9000.net/watched/threads

**Comment by pon4importer** [comment]
At Mon Aug 13 22:23:27 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:12:39 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
