### ISSUE TITLE
Ignoring a person should not hide their posts' position or remove their quotes completely.

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#27]
**[hawke](https://bugs.team9000.net/view_user_page.php?id=59)** reported:

Instead of hiding the post completely, replace the avatar and post itself with a spoiler-like grey bar (similar to the current "you are ignoring this person"). If anyone quotes an ignored person, replace the quote with the same grey bar, just so we know the non-ignored person is quoting someone. Some people can sometimes display a spark of smart outside of their regular routine.

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000028](https://bugs.team9000.net/view.php?id=28)** by **[hawke](https://bugs.team9000.net/view_user_page.php?id=59)** at Sat Feb 11 15:27:13 2012.

**Comment by sonicsnes** [comment]
At Thu May 24 22:26:25 2012:

This is an issue with XenForo, which we no longer support. Ignore support, if present, will be completely different in web.rebuild.

**Comment by pon4importer** [comment]
At Thu Dec 13 02:03:32 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:12:46 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
