### ISSUE TITLE
Chat video not switching to next video

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#3]
**[rileyper](https://bugs.team9000.net/view_user_page.php?id=7)** reported:

Happens to me in firefox mumble says when the next video starts but i just get the end screen blank

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web.chat**
Can reproduce: **sometimes**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000003](https://bugs.team9000.net/view.php?id=3)** by **[rileyper](https://bugs.team9000.net/view_user_page.php?id=7)** at Fri Feb 10 03:03:17 2012.

**Comment by sonicsnes** [comment]
At Fri Feb 10 03:05:56 2012:

Probably caused by TCP losing its mind without having traffic after some amount of time. Adding heartbeats on top of the WebSocket will probably fix this.

**Comment by pon4importer** [comment]
At Sun Feb  3 06:54:15 2013 Mantis issue status **closed**, resolution **duplicate**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:06:00 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
