### ISSUE TITLE
Custom Templates/Save Feature on Forums

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#33]
**[moondoggy23](https://bugs.team9000.net/view_user_page.php?id=14)** reported:

A template feature could be implemented with certain default or custom presets used to give someone a starting point on a thread they can't exactly figure out to start, or custom templates could be used to save someone's progress on a post if they don't have the time to finish it.

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000034](https://bugs.team9000.net/view.php?id=34)** by **[moondoggy23](https://bugs.team9000.net/view_user_page.php?id=14)** at Sun Feb 12 11:35:43 2012.

**Comment by sonicsnes** [comment]
At Fri Feb 17 23:59:22 2012:

What are some use cases for how this feature would be used?

**Comment by pon4importer** [comment]
At Wed Mar 21 10:40:15 2012 **[moondoggy23](https://bugs.team9000.net/view_user_page.php?id=14)** commented:

Default templates could be used for generic-type topics such as organizing a gaming night or some sort of small contest.  The Welcome Thread could be another place with a pre-determined template where the user simply fills in the blanks and it gets posted.  

Custom template/Save template/Post feature could be used by the user to save any long post/reply to a post they are working on, but haven't the time to finish at that particular time.

**Comment by sonicsnes** [comment]
At Thu May 24 22:31:34 2012:

This will not be added until web.rebuild. We are no longer supporting XenForo.

**Comment by pon4importer** [comment]
At Wed Aug 15 04:07:56 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:13:25 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
