### ISSUE TITLE
March 2 Downtime

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#36]
Web provider has reported planned routing instability for

March 2 at 23:00 EST for five hours
At the Atlanta data center.
This will only affect the classic server

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000064](https://bugs.team9000.net/view.php?id=64)** at Tue Feb 28 20:34:42 2012.

**Comment by sonicsnes** [comment]
At Tue Feb 28 20:45:05 2012:

Misread the notice. It appears this will ONLY affect classic.

**Comment by sonicsnes** [comment]
At Mon Aug 13 22:23:27 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:00:10 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
