### ISSUE TITLE
Section For Music Releases

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#37]
**[newspapercrane](https://bugs.team9000.net/view_user_page.php?id=38)** reported:

There is no doubt that Team9000 currently has a growing electronic music creation community.  At present it seems that most of the blog entries posted on team9000 are for the announce/release of music.  Moving the releases (which are primarily hosted on soundcloud and mixCloud.  Moving these releases would allow two things:
*Allow blogs to be less focused on Music releases and more focused on other things.
*Provide a more specialized area where music can be showcased properly
*Attract more artists to team9000

Possible features include:
*Rating System, which allows releases to be voted up, and voted down, allowing artists the ability to retrieve quantitative feedback on releases
*Comments system, allowing artists to receive qualitative feedback on releases
*A "Play All" type feature similar to Team9000 Goggles, allowing listeners to stream songs back to back in a random order.  This will expose users to new/different artists
*A Ranking system based on the overall feedback of a song, as well as how new it is, allowing quality releases to "Trend"

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web.rebuild**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000065](https://bugs.team9000.net/view.php?id=65)** by **[newspapercrane](https://bugs.team9000.net/view_user_page.php?id=38)** at Wed Feb 29 14:39:23 2012.

**Comment by sonicsnes** [comment]
At Thu May 24 22:20:25 2012:

This seems to be more of something that comes and goes in phases. When blogs are removed, the issue of "music always being on the top" should become less of an issue as well. I don't believe this really needs its entire own section.

**Comment by pon4importer** [comment]
At Wed Aug 15 04:07:56 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:00:25 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
