### ISSUE TITLE
Mumble "Local Chat"

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#39]
Users should have the ability to chat within their private room in the chat box. This means each Mumble room will need to tie into its own room on the chat server.

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web.mumble**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000041](https://bugs.team9000.net/view.php?id=41)** at Fri Feb 17 23:58:44 2012.

**Comment by sonicsnes** [comment]
At Mon Aug 13 22:26:12 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:14:07 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
