### ISSUE TITLE
Usergroups aren't checked by chat SSO integration

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#4]
Index chat controller, line 10

Mantis severity: **major**
Mantis priority: **normal**
Mantis project: **web.chat**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000004](https://bugs.team9000.net/view.php?id=4)** at Fri Feb 10 03:08:21 2012.

**Comment by sonicsnes** [comment]
At Mon Aug 13 22:24:02 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:57:03 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
