### ISSUE TITLE
reverse order of server listing

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#40]
**[ollee](https://bugs.team9000.net/view_user_page.php?id=43)** reported:

Currently, when more than one server is listed, it is in ascending order(1, 2, 3...). Unless there is plans for reuse of server id numbers, could we get that flip flopped and get it in descending order(3, 2, 1...)?

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web.launch**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000068](https://bugs.team9000.net/view.php?id=68)** by **[ollee](https://bugs.team9000.net/view_user_page.php?id=43)** at Thu Mar  1 10:59:55 2012.

**Comment by sonicsnes** [comment]
At Thu Mar  1 11:09:36 2012:

Fixed, servers are now grouped into active and retired.

**Comment by pon4importer** [comment]
At Mon Aug 13 22:23:48 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:00:37 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
