### ISSUE TITLE
Comment system on songs

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#41]
-

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web.pon3**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000043](https://bugs.team9000.net/view.php?id=43)** at Sat Feb 18 00:06:12 2012.

**Comment by pon4importer** [comment]
At Tue Feb 18 11:24:47 2014 **[kerzyte](https://bugs.team9000.net/view_user_page.php?id=124)** commented:

No longer applicable

**Comment by sonicsnes** [comment]
At Tue Feb 18 11:24:48 2014 Mantis issue status **closed**, resolution **open**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:14:23 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
