### ISSUE TITLE
Repeatedly Dying after falling into Void in Skylands.

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#43]
**[gabrielbelmont](https://bugs.team9000.net/view_user_page.php?id=119)** reported:

Summary explains the problem. If I respawn, I fall into what looks to be a black hole and die all over again. It continues to repeat. If I manage to type /killme quickly enough before I die again, it respawns me in this same black hole, and I die again. I cannot get out.

Mantis severity: **major**
Mantis priority: **normal**
Mantis project: **game.minecraft**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000071](https://bugs.team9000.net/view.php?id=71)** by **[gabrielbelmont](https://bugs.team9000.net/view_user_page.php?id=119)** at Sun Mar  4 17:37:32 2012.

**Comment by sonicsnes** [comment]
At Sun Mar  4 17:44:55 2012:

This is probably fixed. Please re-open if you continue to experience the issue.

**Comment by sonicsnes** [comment]
At Sun Mar  4 17:50:41 2012:

Please call attention of an admin next time you are online.

**Comment by pon4importer** [comment]
At Mon Aug 13 22:22:31 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:00:49 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
