### ISSUE TITLE
Ignore function

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#45]
**[patchouli](https://bugs.team9000.net/view_user_page.php?id=75)** reported:

While connecting via IRC allows for a user to be ignored, the web chat has no /ignore itself. This would be very useful to those who use the web chat to not have to deal with the random spammers that come in from time to time.

Mantis severity: **feature**
Mantis priority: **normal**
Mantis project: **web.chat**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000047](https://bugs.team9000.net/view.php?id=47)** by **[patchouli](https://bugs.team9000.net/view_user_page.php?id=75)** at Sat Feb 18 19:30:16 2012.

**Comment by pon4importer** [comment]
At Fri Oct 18 02:48:02 2013 **[patchouli](https://bugs.team9000.net/view_user_page.php?id=75)** commented:

Due to friends having harassment issues via text on mumble/chat, I would like to ask this get higher priority to get implemented.

**Comment by sonicsnes** [comment]
At Mon Dec  9 04:51:24 2013:

Fixed

**Comment by pon4importer** [comment]
At Mon Dec  9 04:51:24 2013 Mantis issue status **closed**, resolution **fixed**.
