### ISSUE TITLE
Homepage formatting broke

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#48]
**[3vans](https://bugs.team9000.net/view_user_page.php?id=118)** reported:

My team9000 seems to be broken. At home, when I have no proxy, just my accounts and log out buttons are hanging below the menubar.

When I have a proxy, it looks like the attached. This could be because my school sometimes love to block websites and also .css. It also has a kind of whitelist, too.

Mantis severity: **major**
Mantis priority: **normal**
Mantis project: **web**
Can reproduce: **have not tried**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000122](https://bugs.team9000.net/view.php?id=122)** by **[3vans](https://bugs.team9000.net/view_user_page.php?id=118)** at Fri May 25 08:19:36 2012.

**Comment by pon4importer** [comment]
At Fri May 25 08:19:36 2012 **[3vans](https://bugs.team9000.net/view_user_page.php?id=118)** attached **[Screen shot 2012-05-25 at 6.17.22 PM.png](https://bugs.team9000.net/file_download.php?file_id=14&type=bug)**, 476123 bytes, *image/png*.

**Comment by sonicsnes** [comment]
At Fri May 25 10:46:40 2012:

Does this URL load in your browser?

https://buildr.pon3.org/wwwstyle/css/index

**Comment by pon4importer** [comment]
At Mon Aug 13 22:23:27 2012 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:02:02 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
