### ISSUE TITLE
Clicking chat popup doesn't launch chat

### ISSUE THREAD

**Issue by sonicsnes** [team9000/issues#5]
eventworker.js is missing, and causes the cross-window communication to do nothing.

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web.chat**
Can reproduce: **have not tried**

**Comment by sonicsnes** [comment]
Originally reported as **[mantis:0000005](https://bugs.team9000.net/view.php?id=5)** at Fri Feb 10 03:43:35 2012.

**Comment by sonicsnes** [comment]
At Mon Jan  7 23:43:09 2013 Mantis issue status **closed**, resolution **fixed**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 04:06:16 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
