### ISSUE TITLE
can't drag images into chat

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#6]
**[rileyper](https://bugs.team9000.net/view_user_page.php?id=7)** reported:

can't drag images into chat from desktop/outside browser

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **web.chat**
Can reproduce: **N/A**

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000006](https://bugs.team9000.net/view.php?id=6)** by **[rileyper](https://bugs.team9000.net/view_user_page.php?id=7)** at Fri Feb 10 03:43:38 2012.

**Comment by sonicsnes** [comment]
At Thu Dec 13 02:21:05 2012:

This feature is no longer supported.

**Comment by pon4importer** [comment]
At Thu Dec 13 02:21:05 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:57:11 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
