### ISSUE TITLE
Certain Skylands chunks are very glitchy

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#7]
**[sttheo](https://bugs.team9000.net/view_user_page.php?id=30)** reported:

In Skylands, there seems to be a very weird issue with a few chunks.  They are completely stripped of smoothstone,light doesn't always calculate correctly, sand, water, and gravel don't always fall, and I've encountered a few passive skeletons that don't despawn (even after leaving and reentering Skylands and the server as a whole).

Mantis severity: **minor**
Mantis priority: **low**
Mantis project: **game.minecraft**
Can reproduce: **have not tried**
To reproduce:

[Lack of smoothstone, sand/gravel/water not falling] Travel to Skylands at around x:0 z:0 and look around.
[Skeletons] Travel to around x:24 y:5 z:24, the skeletons just stand there.
[Light not calculating correctly] Find one of the above chunks and build a vertical line of blocks - the light may flicker as if the game cannot decide if you're in sunlight or not.

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000007](https://bugs.team9000.net/view.php?id=7)** by **[sttheo](https://bugs.team9000.net/view_user_page.php?id=30)** at Fri Feb 10 05:14:31 2012.

**Comment by sonicsnes** [comment]
At Fri Feb 10 05:25:25 2012:

Unfortunately, this isn't something we can handle. We use a stock install of this plugin, and it is a bit... quirky at times:

http://dev.bukkit.org/server-mods/skylandsplus/

**Comment by pon4importer** [comment]
At Wed Aug 15 04:07:56 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:57:15 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
