### ISSUE TITLE
cursor issue with text edit menu of forum posts

### ISSUE THREAD

**Issue by pon4importer** [team9000/issues#8]
**[lacar1601](https://bugs.team9000.net/view_user_page.php?id=33)** reported:

The edit text menu of forum posts seems to have a text cursor rendering issue, which makes text editing and tracking more difficult. See Steps To Reproduce below.

Mantis severity: **minor**
Mantis priority: **low**
Mantis project: **web**
Can reproduce: **have not tried**
To reproduce:

Post a forum reply with some random text. Click the "edit" button near the bottom of the post you just made. A wild text menu appears. Use the mouse to set the text cursor in between any two text characters. Notice how the text cursor stops blinking after a short interval of time. Use the arrow keys to move the text cursor between other characters. Observe how the cursor does not move at all. Type in another character. The character appears in the anticipated position that your arrow keys dictated, followed by the cursor, which again stops blinking. Use the mouse to dictate a new position for the text cursor. Notice how the text cursor does not move.

This could be an issue that is localized to my laptop only.

**Comment by pon4importer** [comment]
Originally reported as **[mantis:0000008](https://bugs.team9000.net/view.php?id=8)** by **[lacar1601](https://bugs.team9000.net/view_user_page.php?id=33)** at Fri Feb 10 05:38:39 2012.

**Comment by sonicsnes** [comment]
At Thu May 24 22:40:38 2012:

We are no longer supporting XenForo and its bugs. This issue will be resolved upon the completion of web.rebuild.

**Comment by pon4importer** [comment]
At Wed Aug 15 04:07:56 2012 Mantis issue status **closed**, resolution **invalid**.

**Comment by pon4importer** [comment]
Issue migrated from Mantis to GitHub at Sun Sep 27 03:57:19 2015 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.3
